import logging as log
import os
from datetime import datetime, timezone

import psycopg2
from psycopg2 import sql

log.basicConfig(format="%(asctime)s - %(message)s", level=log.INFO)

# Columns the reader actually writes. The live table has more (ts0, gts, and
# the per-node id/uid pair), but those are either no longer populated or
# generated by the database itself.
REQUIRED_COLUMNS = {"tm", "net", "pwr", "p1", "p2", "n1", "n2", "gas"}


class Dao:
    """Writes YouLess datagrams into an existing TimescaleDB hypertable.

    This class deliberately does NOT create the table. The production schema is
    a hypertable with a compression policy, an id sequence, and a `uid` column
    whose generation expression differs per node ('A' || id on patricia,
    'B' || id on pi4) -- none of which a `CREATE TABLE IF NOT EXISTS` here could
    reproduce. The previous version did exactly that, so a deploy against a
    fresh database would have silently produced a plain table with four dead
    columns and no hypertable, and everything downstream (continuous
    aggregates, compression, the dashboard) would have failed later and less
    obviously.

    Schema lives in deployment/schema.sql.
    """

    def __init__(self, table_name: str = "data"):
        # Expected format: postgresql://user:password@host:port/database
        # or libpq keyword form: host=... port=... dbname=... user=... password=...
        database_url = os.getenv("PG_DSN")
        if not database_url:
            raise ValueError("PG_DSN environment variable is not set")

        self.connection_params = database_url
        self.table_name = table_name
        self._verify_schema()

    def _verify_schema(self):
        """Fail fast and loudly if the target table is missing or wrong."""
        conn = cursor = None
        try:
            conn = psycopg2.connect(self.connection_params)
            cursor = conn.cursor()

            cursor.execute("SELECT to_regclass(%s)", (self.table_name,))
            if cursor.fetchone()[0] is None:
                raise RuntimeError(
                    f"table '{self.table_name}' does not exist. "
                    f"Create it with deployment/schema.sql before starting the reader."
                )

            cursor.execute(
                "SELECT attname FROM pg_attribute "
                "WHERE attrelid = %s::regclass AND attnum > 0 AND NOT attisdropped",
                (self.table_name,),
            )
            present = {r[0] for r in cursor.fetchall()}
            missing = REQUIRED_COLUMNS - present
            if missing:
                raise RuntimeError(
                    f"table '{self.table_name}' is missing column(s): "
                    f"{', '.join(sorted(missing))}. See deployment/schema.sql."
                )

            cursor.execute(
                "SELECT count(*) FROM timescaledb_information.hypertables "
                "WHERE hypertable_name = %s",
                (self.table_name,),
            )
            is_hypertable = cursor.fetchone()[0] > 0
            if not is_hypertable:
                # Not fatal -- inserts still work -- but continuous aggregates
                # and compression do not, so say so rather than fail quietly.
                log.warning(
                    "table '%s' is NOT a hypertable; continuous aggregates and "
                    "compression will not work against it",
                    self.table_name,
                )

            log.info(
                "Connected to PostgreSQL, writing to %s'%s'",
                "hypertable " if is_hypertable else "table ",
                self.table_name,
            )
        except Exception as e:
            log.error(f"Error connecting to database: {e}")
            raise
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()

    def latest_tm(self):
        """Newest timestamp already stored, or None if the table is empty.

        The reader seeds its duplicate check with this on startup. Without it,
        a restart re-writes whatever sample is current at that moment, even if
        the previous process already stored it -- which is where the 28
        duplicate timestamps between 2025-08 and 2026-01 came from.
        """
        conn = cursor = None
        try:
            conn = psycopg2.connect(self.connection_params)
            cursor = conn.cursor()
            cursor.execute(
                sql.SQL("SELECT max(tm) FROM {}").format(sql.Identifier(self.table_name))
            )
            return cursor.fetchone()[0]
        except Exception as e:
            # Never block startup on this -- worst case we risk one duplicate.
            log.warning("could not read latest tm (%s); starting without a seed", e)
            return None
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()

    def add(self, datagram: dict):
        # Convert Unix timestamp to datetime for 'tm' field
        converted_datagram = datagram.copy()
        if "tm" in converted_datagram:
            converted_datagram["tm"] = datetime.fromtimestamp(
                converted_datagram["tm"], tz=timezone.utc
            )

        keys = list(converted_datagram.keys())
        values = tuple(converted_datagram.values())

        # Build parameterized query for PostgreSQL
        columns = sql.SQL(", ").join(map(sql.Identifier, keys))
        placeholders = sql.SQL(", ").join(sql.Placeholder() * len(keys))
        statement = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
            sql.Identifier(self.table_name), columns, placeholders
        )

        conn = None
        cursor = None

        try:
            conn = psycopg2.connect(self.connection_params)
            cursor = conn.cursor()
            cursor.execute(statement, values)
            log.debug(f"ran {statement.as_string(conn)} with values {values}")
            conn.commit()
        except Exception as e:
            if conn:
                conn.rollback()
            raise
        finally:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
